### ISSUE TITLE
Script allows numeric arguments though it shouldn't

### ISSUE THREAD

**Issue by antweiss** [rbalashevich/bash-exercises#10]
Input:
`./exercise1.sh apple 15 fruit 22 33 55`

Output:
```
Number of arguments: 6
1st argument: apple
2nd argument: 15
3nd argument: fruit
more arguments: 22, 33, 55,
Name: apple
Count: 15
Type: fruit
```

```
cat ~/mylogs/apple.log
1) 33: alert
2) 55: alert
3) 22: warning
4) 55: normal
5) 22: failure
6) 33: error
7) 33: request
8) 55: request
9) 22: request
10) 22: request
11) 55: normal
12) 33: notice
13) 22: warning
14) 33: warning
15) 22: failure
```

**Comment by rbalashevich** [comment]
$ ./exercise1.sh Apple 10 Fruit one two three operand 2344
Number of arguments: 8
1st argument: Apple
2nd argument: 10
3nd argument: Fruit
Additional arguments: one two three operand 2344 
Old file Apple.log removed.
🧮 Argument counter in array is 1 now
🔬 Dumping argument, it is "Apple" now. Checking is it a numeric or not
🧮 Argument counter in array is 2 now
🔬 Dumping argument, it is "10" now. Checking is it a numeric or not
🧮 Argument counter in array is 3 now
🔬 Dumping argument, it is "Fruit" now. Checking is it a numeric or not
🧮 Argument counter in array is 4 now
🔬 Dumping argument, it is "one" now. Checking is it a numeric or not
🧮 Argument counter in array is 5 now
🔬 Dumping argument, it is "two" now. Checking is it a numeric or not
🧮 Argument counter in array is 6 now
🔬 Dumping argument, it is "three" now. Checking is it a numeric or not
🧮 Argument counter in array is 7 now
🔬 Dumping argument, it is "operand" now. Checking is it a numeric or not
🧮 Argument counter in array is 8 now
🔬 Dumping argument, it is "2344" now. Checking is it a numeric or not
🔢 Error: one of additional parameters is numeric and not a string! Exiting.
