### ISSUE TITLE
The script only prints 1 line into log file

### ISSUE THREAD

**Issue by antweiss** [rbalashevich/bash-exercises#3]
./name_count.sh apple 100 fruit one two three operand
Name: apple
Count: 100
Type: fruit

cat ~/mylogs/apple.log
fruit: error

**Comment by antweiss** [comment]
Still happening:

```
./exercise1.sh apple 100 fruit one two three operand
Number of arguments: 7
1st argument: apple
2nd argument: 100
3nd argument: fruit
more arguments: one, two, three
Name: apple
Count: 100
Type: fruit
```

`cat ~/mylogs/apple.log
fruit: failure`

**Comment by antweiss** [comment]
@rbalashevich please reopen this issue and fix

**Comment by rbalashevich** [comment]
Investigated
