### ISSUE TITLE
The script ignores optional arguments

### ISSUE THREAD

**Issue by antweiss** [rbalashevich/bash-exercises#4]

**Comment by antweiss** [comment]
@rbalashevich just recalled you never finalized this exercise
Please get back to it when you see it and take care of all the issues I opened.

**Comment by rbalashevich** [comment]
Seems to be ++i in loop is ignored. Why?

**Comment by antweiss** [comment]
no, the loop isn't ignored.
Try running the script with `-x` in the shebang line and you'll see what's happening.

**Comment by rbalashevich** [comment]
`-x` helped a lot.
